[package]
name = "advent-of-code-2016"
version = "0.1.0"
edition = "2024"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
md5 = "0.8.0"
rayon = "1.11.0"
smallvec = "1.15.1"
test-case = "3.3.1"
thiserror = "2.0.16"
